# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eb649126b8eb37d3c2a25b4c3d2c2acf130f4f7ca62dc90500103ffcd1662a4186edabdc76e4a50ca9f31114242a67bb840fd6ed56a8e923b816606fc3fc0b3
  secret_key_base: f487fbbd35d7d23634ad6d5f02d3c54b4d3b82561670b17c4986a2ee774e2bbdedf954ab12ed3382929ec9dd1af06be3c8ad9f2815acb6237a4e10345dee6526
  email_provider_username: app37375907@heroku.com
  email_provider_password: qzhnrp9u6921
  domain_name: mecpartners.it

test:
  secret_key_base: 2ee1b2187df86f4750e86217433cdfdeb2a7571f9dc77f62e17f312814aadbdbf36ab6762fc94d0e9d2ac289a7395845477c726f665276a286d3a547b4eac24a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  email_provider_username: <%= ENV["SENDGRID_USERNAME"] %>
  email_provider_password: <%= ENV["SENDGRID_PASSWORD"] %>
  domain_name: mecpartners.it
